### ISSUE TITLE
Test of using GitHub issues for field operations concerns

### ISSUE THREAD

**Issue by joshuamckenty** [Traitis/website#2]
Here are the reasons to create a GitHub issue:

 * It generates an ID that we can use to name a slack channel.
 * It provides an email interface for folks (like customers) who might not have access to internal slack.
 * It has a clear historical status label
 * It can be used to mention people who might be offline at the moment, but they have to be members of the repository team. 
* It can have files attached if relevant (again, from a web interface or email attachment, and not requiring use of Slack or git).

**Comment by joshuamckenty** [comment]
At Pivotal, the incident response process always started with creating a Slack channel named after the Issue ID or Trouble Ticket ID.

**Comment by mdfischer** [comment]
I'm commenting on this issue

**Comment by mdfischer** [comment]
So did it not create a LOT of slack channels to do it this way, or were people good about resolving issues quickly and deleting the channels afterward?

**Comment by joshuamckenty** [comment]
I’m replying to your comment in an email.

**Comment by joshuamckenty** [comment]
Done.

**Comment by joshuamckenty** [comment]
The Slack channels were private to the assigned team, and archived once the incident was closed.
